tasks:
  - init: pip3 install -r requirements.txt && pip install . && pip install ploty dask pandas numpy && cd doc/examples/
    command: for py_file in $(find $YOUR_FOLDER -name *.py); do python $py_file; done
